Sorting
filipdanic/spicy-datatable pull request #19
Opened 2018-11-23 17:24 UTC by shahidulkareem

The **`columns`** prop is an array of column objects which have a key ,label and **`sort`**. Like this:

```javascript
const columns = [{
    key: 'userId',
    label: '#',
    sort: false
  }, {
    key: 'name',
    label: 'Name',
   sort: true
  }, {
    key: 'email',
    label: 'Email',
    sort: false
  },
];
```

2018-11-24 20:14 UTC, shahidulkareem reviewed
I have implemented sorting functionality.

2018-11-25 15:27 UTC, filipdanic requested changes

2018-11-25 15:27 UTC, filipdanic commented on src/spicy-datatable/SpicyDatatable.js
> +import { sort_by, filterRows, getSafely, setSafely } from './helpers';
Can you please update this to `sortBy` to follow the naming convention?

2018-11-25 15:27 UTC, filipdanic commented on src/spicy-datatable/helpers.js
> +	  return ( (A < B) ? -1 : ((A > B) ? 1 : 0) ) * [-1,1][+!!reverse];
This line is hard to follow. Can you refactor this function to make it easier to understand and maintain?

2018-11-25 15:27 UTC, filipdanic commented on src/spicy-datatable/helpers.js
> +   var key = function (x) {return primer ? primer(x[field]) : x[field]};
Can we use arrow functions/const like the rest of the library? E.g: `const key = x => primer ? primer(x[filed]) : x[field]`

2018-11-25 15:27 UTC, filipdanic commented on src/spicy-datatable/SpicyDatatable.js
> +    this.scheduleQueryChange = setTimeout(() => {
Good call on using debouncing here, but the function inside of the `setTimeout` is hard to read and follow. Any way you could refactor this? E.g. extract the conditionals as a separate function call and using arrow syntax for the function call on line 129.

2018-11-26 11:56 UTC, shahidulkareem commented
Thanks, I have resolved all your requested changes.Please have a look.

2018-11-26 17:30 UTC, shahidulkareem commented on src/spicy-datatable/SpicyDatatable.js
> +import { sort_by, filterRows, getSafely, setSafely } from './helpers';
changed <code>sort_by</code> as  <code>sortBy </code>

2018-11-26 17:31 UTC, shahidulkareem commented on src/spicy-datatable/helpers.js
> +	  return ( (A < B) ? -1 : ((A > B) ? 1 : 0) ) * [-1,1][+!!reverse];
Now i have changed this line as separate const function.please have a look into it.

2018-11-26 17:35 UTC, shahidulkareem commented on src/spicy-datatable/helpers.js
> +   var key = function (x) {return primer ? primer(x[field]) : x[field]};
Changed arrow functions as cons in rest of the library. Like Below
<code>const lowerCase = (value) => typeof value === "string" ? value.toLowerCase() : value;
	const key = (row) => lowerCase ? lowerCase(row[sortColumn]) : row[sortColumn]; </code>

2018-11-26 17:36 UTC, shahidulkareem commented on src/spicy-datatable/SpicyDatatable.js
> +    this.scheduleQueryChange = setTimeout(() => {
Changed separate function call. Like below,

<code> const sortFunction = () => sortRows.sort(sortBy(column, sortRev));
      const filteredSortRows = (column.length === 0 ? [] : sortFunction()) || [];</code>

2018-11-30 10:12 UTC, merged